# Generated by Django 5.1 on 2024-09-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_song_album_song_duration_song_spotify_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_img',
            field=models.URLField(),
        ),
    ]
